resources:
- statefulset.yaml
- services.yaml

# TODO: have a configmap.yaml and secret.yaml in this directory so that we can deploy this base
# without kustomization? Would need to handle the files node.cnf, entrypoint.sh, functions.sh.

# This config means whenever MYSQL_SERVICE contains a name matching a Service name (it should,
# always) and the Service name is changed (e.g. with a namePrefix) the MYSQL_SERVICE value should
# be updated correspondingly.
configurations:
- ./kustomizeconfig/namereference.yaml

configMapGenerator:
- name: mysql-config-files
  files:
  - node.cnf
- name: mysql-startup-scripts
  files:
  - entrypoint.sh
  - functions.sh
- name: mysql
  literals:
  - MYSQL_USER=mysql
  - MYSQL_DATABASE=default
  - ALLOW_ROOT_FROM='%'
  - PXC_STRICT_MODE=ENFORCING
  - DEBUG="true"
  - MYSQL_SERVICE=mysql

secretGenerator:
- name: mysql
  literals:
  - MYSQL_PASSWORD=oyMxgZChuu
  - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
  - XTRABACKUP_PASSWORD=4WHuZ4xTLq
