apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.48.1
    app.kubernetes.io/component: controller
  name: ingress-nginx
automountServiceAccountToken: true
