namespace: ingress-nginx

resources:
- ns.yaml
- controller-serviceaccount.yaml
- controller-configmap.yaml
- controller-clusterrole.yaml
- controller-clusterrolebinding.yaml
- controller-role.yaml
- controller-rolebinding.yaml
- controller-service-webhook.yaml
- controller-service.yaml
- controller-deployment.yaml
- validating-webhook.yaml
- serviceaccount.yaml
- admission-clusterrole.yaml
- admission-clusterrolebinding.yaml
- role.yaml
- rolebinding.yaml
- job-create-secret.yaml
- job-patch-webhook.yaml
