resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: ml-api-adapter-service
  literals:
  - LOG_LEVEL=silly
  - CSL_LOG_TRANSPORT=console
  - LIB_RESOURCE_VERSIONS=transfers=1.1,participants=1.0,quotes=1.0
